---
- name: Configurar y ejecutar NGINX en contenedor Docker remoto
  hosts: web
  become: true

  tasks:
    - name: Asegurar que Docker está corriendo
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true

    - name: Crear directorio para la configuración de NGINX
      ansible.builtin.file:
        path: /etc/nginx/conf.d
        state: directory
        mode: '0755'

    - name: Subir archivo de configuración de NGINX
      ansible.builtin.copy:
        src:  /home/debian/web/templates/default.conf.j2
        dest: /etc/nginx/nginx.conf
        owner: root
        group: root
        mode: '0644'

    - name: Subir archivo server
      ansible.builtin.copy:
        src:  /home/debian/web/templates/server.conf.j2
        dest: /etc/nginx/conf.d/server.conf
        owner: root
        group: root
        mode: '0644'

    
    - name: Subir certificado SSL
      ansible.builtin.copy:
        src:  /etc/ssl/certs/certificado.crt
        dest: /etc/ssl/certs/nginx.crt
        owner: root
        group: root
        mode: '0644'

    - name: Subir clave privada SSL
      ansible.builtin.copy:
        src: /etc/ssl/private/private.key
        dest: /etc/ssl/private/nginx.key
        owner: root
        group: root
        mode: '0600'

    - name: Detener y eliminar contenedor existente (si existe)
      ansible.builtin.command:
        cmd: docker rm -f https-jose
      ignore_errors: true

    - name: Lanzar contenedor Docker para NGINX
      ansible.builtin.command:
        cmd: >
          docker run -d -p 4430:443 -p 8080:80
          --name https-jose
          -v /etc/ssl/certs:/etc/ssl/certs
          -v /etc/ssl/private:/etc/ssl/private
          -v /etc/nginx/conf.d:/etc/nginx/conf.d
          nginx

   
