apiVersion: apps/v1
kind: Deployment
metadata:
  name: ldap-deployment
  labels:
    app: ldap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ldap
  template:
    metadata:
      labels:
        app: ldap
    spec:
      containers:
        - name: ldap
          image: 512007083666.dkr.ecr.us-east-1.amazonaws.com/web:ldap
          imagePullPolicy: Always
          ports:
            - containerPort: 389
            - containerPort: 636
          env:
            - name: LDAP_ORGANISATION
              value: "jose FTP"
            - name: LDAP_DOMAIN
              value: "jose ftp.com"
            - name: LDAP_ADMIN_PASSWORD
              value: "admin-ldap"
      imagePullSecrets:
        - name: regcred
