name: lanzar-ftps-ldap

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: "us-east-1"

      - name: Clave SSH
        run: echo "${{ secrets.SSH_PRIVATE_KEY }}"

      - name: Terraform Init
        run: terraform init
        working-directory: .

      - name: Terraform Plan
        run: terraform plan
        working-directory: .

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: .

      # Guardar el archivo terraform.tfstate como artefacto
      - name: Upload Terraform State as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: terraform_state
          path: terraform.tfstate

  upload_to_s3:
    runs-on: ubuntu-latest
    needs: terraform

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: "us-east-1"

      # Descargar el artefacto terraform.tfstate y guardarlo en la caché
      - name: Download Terraform State Artifact
        uses: actions/download-artifact@v4
        with:
          name: terraform_state
          path: ./terraform_cache

      # Mover el archivo descargado al nombre esperado para subirlo a S3
      - name: Move State File to Root Directory
        run: mv ./terraform_cache/terraform.tfstate terraform.tfstate

      # Subir el archivo a S3
      - name: Upload Terraform State to S3
        run: |
          aws s3 cp terraform.tfstate s3://artefacto-tf/terraform_state.tfstate
