name: Terraform AWS Deployment
on:
  push:
    branches:
      - terraform
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: install terraform
        uses: hashicorp/setup-terraform@v3
      - name: aws credecials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: "us-east-1"  # Cambia a la región de AWS que estás usando
      - name: init terraform
        run: terraform init
        working-directory: .
      - name: Plan Terraform
        run: terraform plan 
      - name: Apply Terraform
        run: terraform apply -auto-approve
        working-directory: .
      - name: upload terraform state
        uses: actions/upload-artifact@v4
        with: 
          name: terraform_state
          path: terraform.tfstate
