name: Terraform AWS Deployment
on:
 push:
 branches:
    - terraform
jobs:
   terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: configurar terraform
        uses: hashicorp/setup-terraform@v3
      - name: CONFIGURAR CREDENCIALES AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_session_token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: "us-east-1" 
          
      - name: init terraform
        run: terraform init
        working-directory: .
      - name: Plan Terraform
        run: terraform plan
        working-directory: .
      - name: Apply Terraform
        run: terraform aplay -auto-approve
        working-directory: .
      - name: upload-terreform-state
        uses: actions/upload-artifact@v4
        with: 
          name: terraform-state
          path: terraform.tfstate
            
